spring.application.name=Projekt2_Gruppe_1_Oenskeskyen

spring.datasource.url=jdbc:mysql://localhost:3306/oenskeskyen
spring.datasource.username=root
spring.datasource.password=

#Husk at skifte password, username og evt. url